/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.sistemas.view;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import uni.sistemas.controller.Controller;

import uni.sistemas.entity.Empleado;

/**
 *
 * @author EQUIPO
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cmbC = new javax.swing.JComboBox<>();
        rbt1 = new javax.swing.JRadioButton();
        rbt2 = new javax.swing.JRadioButton();
        rbt3 = new javax.swing.JRadioButton();
        btnA = new javax.swing.JButton();
        txtS = new javax.swing.JTextField();
        txtL = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnG = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl1.setBorder(new javax.swing.border.MatteBorder(null));
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Cargo", "Area", "Sueldo", "Descuento", "Sueldo neto"
            }
        ));
        jScrollPane2.setViewportView(tbl1);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Cargo");

        jLabel4.setText("Area");

        jLabel5.setText("Sueldo");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        cmbC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Director Ejecutivo", "Jefe de marca", "Recepcionista", "Asistente personal" }));
        cmbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt1);
        rbt1.setText("Contabilidad");
        rbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt2);
        rbt2.setText("Informatica");
        rbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt3);
        rbt3.setText("Publicidad");
        rbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt3ActionPerformed(evt);
            }
        });

        btnA.setText("Agregar");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        txtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSActionPerformed(evt);
            }
        });

        txtL.setText("Mostrar");
        txtL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLActionPerformed(evt);
            }
        });

        btnAc.setText("Actualizar");
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });

        btnB.setText("Borrar");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo");

        jLabel7.setText("No funciona para agregar");

        btnE.setText("Existe");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Si ya tiene el archivo creado HAGA CLICK EN CARGAR PARA CARGAR EL ARCHIVO Y QUE EL CONTADOR DE REGISTROS CUENTE CUANTOS HAY PARA QUE AL ALMACENAR NUEVOS REGISTROS NO SE REPITA EL CODIGO\nPara agregar llene los campos menos codigo(si lo llena igual no afecta en el desempeño)\nPara mostrar lo ingresado haga click en MOSTRAR, se listara sin codigos repetidos\nPara guardar los registros, presione GUARDAR.\nPara actualizar y borrar es necesrio primero verificar si EXISTE el registro mediante exclusivamente el codigo, una vez hecho \neso se podra seleccionar actualizar y borrar.\nSE RECOMIENDA CARGAR LOS ARCHIVOS ANTES DE LOS INGRESOS DE LOS NUEVOS REGISTROS");
        jScrollPane1.setViewportView(jTextArea1);

        btnG.setText("Guardar");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnC.setText("Cargar");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("1- Cargar(si existe)\n2- Ingresar registros\n3- actualizarlos o eliminarlos\n4- Guardar\n\nAL ACTUALIZAR ,LLENE TODOS LOS CAMPOS");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnA)
                                .addGap(34, 34, 34)
                                .addComponent(txtL)
                                .addGap(18, 18, 18)
                                .addComponent(btnAc)
                                .addGap(33, 33, 33)
                                .addComponent(btnB)
                                .addGap(29, 29, 29)
                                .addComponent(btnG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnC))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombre)
                                    .addComponent(txtApellido)
                                    .addComponent(cmbC, 0, 159, Short.MAX_VALUE)
                                    .addComponent(txtcod, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbt1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbt2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtS)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbt3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(rbt1)
                                    .addComponent(rbt2)
                                    .addComponent(rbt3)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnA)
                            .addComponent(txtL)
                            .addComponent(btnAc)
                            .addComponent(btnB)
                            .addComponent(btnG)
                            .addComponent(btnC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbt2ActionPerformed

    private void cmbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cmbCActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtApellidoActionPerformed

    private void rbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbt1ActionPerformed


    private void rbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbt3ActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:

        procesar1();
    }//GEN-LAST:event_btnAActionPerformed

    private void txtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtSActionPerformed

    private void txtLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLActionPerformed
        // TODO add your handling code here:
        procesar();

    }//GEN-LAST:event_txtLActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed

        procesar3();

    }//GEN-LAST:event_btnAcActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            procesar2();
        } catch (Exception ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        procesar4();
    }//GEN-LAST:event_btnBActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        try {
            procesar5();
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        procesar6();
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton rbt1;
    private javax.swing.JRadioButton rbt2;
    private javax.swing.JRadioButton rbt3;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JButton txtL;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    Controller control = new Controller();

    private void procesar() {
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        model.setRowCount(0);
        List<Empleado> aux2 = control.EmpleadoMostrar2();

        for (Empleado em : aux2) {
            Object[] dato2 = {em.getCodigo(), em.getNombre(), em.getApellido(), em.getCargo(), em.getArea(), em.getSueldoT(), em.getSueldoN(), em.getDescuento()};
            model.addRow(dato2);
        }

    }

    private void procesar1() {
        Empleado e = new Empleado();
        String n = txtnombre.getText();
        e.setNombre(n);

        n = txtApellido.getText();
        e.setApellido(n);

        int num = cmbC.getSelectedIndex();
        e.setCargo(Controller.Cargo(num));

       if (rbt1.isSelected()) {
            n = rbt1.getText();
        }
        if (rbt2.isSelected()) {
            n = rbt2.getText();
        }
        if (rbt3.isSelected()) {
            n = rbt3.getText();
        }
        e.setArea(n);
        Double num2 = Double.parseDouble(txtS.getText());
        e.setSueldoT(num2);
        e.setDescuento(Controller.Descuento(num2));
        e.setSueldoN(Controller.Sueldo(num2));
        txtcod.setText("");
        txtnombre.setText("");
        txtApellido.setText("");
        txtS.setText("");
        buttonGroup1.clearSelection();
        control.EmpleadoAgregar(e);
    }

    private void procesar2() throws Exception {
        Empleado e;
        String n = txtcod.getText();

        if (control.existe(n) != null) {

            e = control.existe(n);
            txtcod.setText(e.getCodigo());
            txtnombre.setText(e.getNombre());
            txtApellido.setText(e.getApellido());
            txtS.setText(e.getSueldoT() + "");
        }

    }

    private void procesar3() {
        Empleado e = new Empleado();

        String n = txtcod.getText();
        e.setCodigo(n);

        n = txtnombre.getText();
        e.setNombre(n);

        n = txtApellido.getText();
        e.setApellido(n);

        int num = cmbC.getSelectedIndex();
        e.setCargo(Controller.Cargo(num));

        if (rbt1.isSelected()) {
            n = rbt1.getText();
        }
        if (rbt2.isSelected()) {
            n = rbt2.getText();
        }
        if (rbt3.isSelected()) {
            n = rbt3.getText();
        }
        e.setArea(n);

        Double num2 = Double.parseDouble(txtS.getText());
        e.setSueldoT(num2);
        e.setDescuento(Controller.Descuento(num2));
        e.setSueldoN(Controller.Sueldo(num2));

        control.EmpleadoActualizar(e);
    }

    private void procesar4() {
        Empleado e = new Empleado();

        String n = txtcod.getText();
        e.setCodigo(n);

        control.EmpleadoEliminar(e);
    }

    private void procesar5() throws IOException {
        FileWriter fw;
        FileReader fr;
        File f;
        PrintWriter pw;

        String archivo = "Empleados.txt";
        f = new File(archivo);
        if (f.exists()) {
            f.delete();
        }

        try {
            fw = new FileWriter(archivo, true);

            pw = new PrintWriter(fw);

            for (Empleado em : control.EmpleadoMostrar2()) {

                pw.write(em.toString());
            }

            pw.close();

        } catch (IOException ex) {
            throw ex;
        } finally {

        }

    }

    private void procesar6() {
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        List<Empleado> aux = control.EmpleadoMostrar();
        //  List<Empleado> MOSTRAR = control.EmpleadoMostrar2();
        for (Empleado em : aux) {
            Object[] dato = {em.getCodigo(), em.getNombre(), em.getApellido(), em.getCargo(), em.getArea(), em.getSueldoT(), em.getSueldoN(), em.getDescuento()};
            model.addRow(dato);
        }
        for (Empleado em : aux) {
            control.getContr().getArr().add(em);
        }

    }
}
